In [2]:
import sqlite3
import pandas as pd

# Establish a connection to the SQLite database
conn = sqlite3.connect('./database/IPL_Prediction_Analysis.db')

# Load a table into a pandas DataFrame
df = pd.read_sql_query("SELECT * FROM Batting", conn)

# Close the connection
conn.close()

In [3]:
df

,Batting_ID,Innings,Venue,Team,Start_Date,End_Date,Player_name,Dismissal_type,Runs,Balls,Dot_Balls,Fours,Sixes,Strike_Rate
0,1,1st match (N),Bengaluru,KKR,18-April-2008,18-April-2008,Sourav Ganguly c,c Kallis b Khan,10,12,,2,0,83.33
1,2,1st match (N),Bengaluru,KKR,18-April-2008,18-April-2008,Brendon McCullum,not out,158,73,,10,13,216.43
2,3,1st match (N),Bengaluru,KKR,18-April-2008,18-April-2008,Ricky Ponting,c Kumar b Kallis,20,20,,1,1,100.00
3,4,1st match (N),Bengaluru,KKR,18-April-2008,18-April-2008,David Hussey,c White b Noffke,12,12,,1,0,100.00
4,5,1st match (N),Bengaluru,KKR,18-April-2008,18-April-2008,Mohammad Hafeez,not out,5,3,,1,0,166.66
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16747,16748,67th Match (N),Wankhede,MI,17-May-2024,17-May-2024,Ishan Kishan,b NaveenulHaq,14,15,50,1,0,93.33
16748,16749,67th Match (N),Wankhede,MI,17-May-2024,17-May-2024,Hardik Pandya c,c NaveenulHaq b Mohsin Khan,16,13,10,1,1,123.07
16749,16750,67th Match (N),Wankhede,MI,17-May-2024,17-May-2024,Nehal Wadhera,c Pandya b Ravi Bishnoi,1,3,3,0,0,33.33
16750,16751,67th Match (N),Wankhede,MI,17-May-2024,17-May-2024,Naman Dhir,not out,62,28,31,4,5,221.42
16751,16752,67th Match (N),Wankhede,MI,17-May-2024,17-May-2024,Romario Shepherd,not out,1,1,2,0,0,100.00

In [22]:
import pandas as pd

# Load the data into a pandas DataFrame
df = pd.read_sql_query("SELECT * FROM MVP_Data", conn)

# Convert the Start_Date column to datetime objects
df['Start_Date'] = pd.to_datetime(df['Start_Date'], format='%d-%B-%Y')

# Filter the data for the year 2023
df_2024 = df[df['Start_Date'].dt.year == 2023]

# Filter the data for the SRH and RR teams
df_team = df_2024[(df_2024['Team'] == 'SRH') | (df_2024['Team'] == 'RR')]

# Convert the Total_Impact column to float
df_team['Total_Impact'] = pd.to_numeric(df_team['Total_Impact'], errors='coerce')

# Sort the data by the Total_Impact column in descending order
df_sorted = df_team.sort_values('Total_Impact', ascending=False)

# Print the top 5 players
print(df_sorted.head(11))

       MVP_ID           Innings         Venue Start_Date       End_Date  \
21881   21882    42nd Match (N)      Wankhede 2023-04-30  30-April-2023
22429   22430    65th Match (N)     Hyderabad 2023-05-18    18-May-2023
22119   22120    52nd Match (N)        Jaipur 2023-05-07    07-May-2023
21834   21835    40th Match (N)         Delhi 2023-04-29  29-April-2023
22214   22215    56th Match (N)  Eden Gardens 2023-05-11    11-May-2023
22358   22359    62nd Match (N)     Ahmedabad 2023-05-15    15-May-2023
21283   21284    17th Match (N)       Chennai 2023-04-12  12-April-2023
21329   21330    19th Match (N)  Eden Gardens 2023-04-14  14-April-2023
22525   22526  69th Match (D/N)      Wankhede 2023-05-21    21-May-2023
21426   21427    23rd Match (N)     Ahmedabad 2023-04-16  16-April-2023
22215   22216    56th Match (N)  Eden Gardens 2023-05-11    11-May-2023

               Player_Name Team  Total_Impact  Runs  Balls_Faced Impact_Runs  \
21881     Yashasvi Jaiswal   RR        172.90   124           62      144.62
22429     Heinrich Klaasen  SRH        151.96   104           51      128.05
22119     Yuzvendra Chahal   RR        146.84     0            0           -
21834      Abhishek Sharma  SRH        137.03    67           36          84
22214     Yashasvi Jaiswal   RR        112.84    98           47      111.74
22358    Bhuvneshwar Kumar  SRH        108.84    27           26       27.34
21283  Ravichandran Ashwin   RR         98.77    30           22       29.55
21329          Harry Brook  SRH         98.68   100           55      104.72
22525       Mayank Agarwal  SRH         94.73    83           46       90.38
21426         Sanju Samson   RR         93.68    60           32       76.17
22215     Yuzvendra Chahal   RR         92.23     0            0           -

      Batting_Impact Wickets  Runs_Conceded Impact_Wickets Bowling_Impact
21881          172.9       -            NaN              -              0
22429         151.96       -            NaN              -              0
22119              0       4           29.0           6.58         146.84
21834            100       1           26.0           1.61          37.03
22214         112.84       -            NaN              -              0
22358          17.35       5           30.0           5.13          91.48
21283          28.31       2           25.0           2.91          70.47
21329          98.68       -            NaN              -              0
22525          94.73       -            NaN              -              0
21426          93.68       -            NaN              -              0
22215              0       4           25.0           4.27          92.23

C:\Users\anilw\AppData\Local\Temp\ipykernel_16752\3213024156.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_team['Total_Impact'] = pd.to_numeric(df_team['Total_Impact'], errors='coerce')

In [26]:
import glob
import pandas as pd

# Define the path to the csv folder
csv_folder_path = 'csv'

# Use glob to find all the csv files in the folder
csv_files = glob.glob(f'{csv_folder_path}/*.csv')

# Check if any csv files were found
if not csv_files:
    print('Error: No CSV files found in the specified folder.')
else:
    # Initialize an empty list to store the dataframes
    dfs = []

    # Loop through the csv files and append each dataframe to the list
    for csv_file in csv_files:
        df = pd.read_csv(csv_file)
        dfs.append(df)

    # Merge the first two dataframes in the list
    merged_df = pd.merge(dfs[0], dfs[1], on=['Innings', 'Venue', 'Start_Date', 'End_Date'])

    # Loop through the remaining dataframes and merge them with the merged_df dataframe
    for i in range(2, len(dfs)):
        merged_df = pd.merge(merged_df, dfs[i], on=['Innings', 'Venue', 'Start_Date', 'End_Date'])

    # Print the first few rows of the merged dataframe to verify that it was created correctly
    print(merged_df.head())

KeyError: 'Innings'

In [27]:
import glob
import pandas as pd

# Define the path to the csv folder
csv_folder_path = 'csv'

# Use glob to find all the csv files in the folder
csv_files = glob.glob(f'{csv_folder_path}/*.csv')

# Check if any csv files were found
if not csv_files:
    print('Error: No CSV files found in the specified folder.')
else:
    # Initialize an empty list to store the dataframes
    dfs = []

    # Loop through the csv files and append each dataframe to the list
    for csv_file in csv_files:
        df = pd.read_csv(csv_file)

        # Rename the columns in each dataframe to make them consistent
        if 'Batting_ID' in df.columns:
            df = df.rename(columns={'Batting_ID': 'ID', 'Innings': 'Inning', 'Venue': 'Venue', 'Team': 'Team', 'Start Date': 'Start_Date', 'End Date': 'End_Date', 'BATTING': 'Player', 'Dismissal type': 'Dismissal_Type', 'R': 'Runs', 'B': 'Balls', 'M': 'Minutes', '4s': 'Fours', '6s': 'Sixes', 'SR': 'Strike_Rate'})
        elif 'Bowling_Player' in df.columns:
            df = df.rename(columns={'Inning': 'Inning', 'Venue': 'Venue', 'Team': 'Team', 'Start Date': 'Start_Date', 'End Date': 'End_Date', 'Bowling_Player': 'Player', 'Wickets': 'Wickets', 'M': 'Maidens', 'R': 'Runs', 'W': 'Wides', 'NB': 'No_Balls', 'ECON': 'Economy', '0s': 'Dot_Balls', '4s': 'Fours', '6s': 'Sixes'})
        elif 'Innings' in df.columns and 'Team1' in df.columns:
            df = df.rename(columns={'Innings': 'Inning', 'Venue': 'Venue', 'Start_Date': 'Start_Date', 'End_Date': 'End_Date', 'Team1': 'Team', 'Team1_runs': 'Runs', 'Team1_wickets': 'Wickets', 'Team2_runs': 'Target', 'Team1_played_Overs': 'Played_Overs', 'Team1_Max_Overs': 'Max_Overs', 'Match_Result': 'Result'})
        elif 'MVP_ID' in df.columns:
            df = df.rename(columns={'MVP_ID': 'ID', 'Innings': 'Inning', 'Venue': 'Venue', 'Start_Date': 'Start_Date', 'End_Date': 'End_Date', 'Player_Name': 'Player', 'Team': 'Team', 'Total_Impact': 'Total_Impact_Points', 'Runs': 'Runs', 'Impact_Runs': 'Impact_Runs_Points', 'Batting_Impact': 'Batting_Impact_Points', 'Bowl': 'Wickets', 'Impact_Wickets': 'Impact_Wicket_Points', 'Bowling_Impact': 'Bowling_Impact_Points', 'Balls_Faced': 'Balls_Faced', 'Runs_Conceded': 'Runs_Conceded'})
        elif 'Over_ID' in df.columns:
            df = df.rename(columns={'Over_ID': 'ID', 'Innings': 'Inning', 'Venue': 'Venue', 'Start_Date': 'Start_Date', 'End_Date': 'End_Date', 'Team_Name': 'Team', 'Overs': 'Overs', 'Team_Runs': 'Runs', 'Team_Wickets': 'Wickets', 'Team_Total_Runs': 'Total_Runs', 'Team_Total_Wickets': 'Total_Wickets'})
        elif 'Innings' in df.columns and 'Player1' in df.columns:
            df = df.rename(columns={'Innings': 'Inning', 'Venue': 'Venue', 'Start_Date': 'Start_Date', 'End_Date': 'End_Date', 'Team': 'Team', 'Player1': 'Player1', 'Player1_Runs': 'Runs1', 'Player1_Balls': 'Balls1', 'Partnership_Runs': 'Partnership_Runs', 'Partnership_Balls': 'Partnership_Balls', 'Player2_Runs': 'Runs2', 'Player2_Balls': 'Balls2'})

        dfs.append(df)

    # Merge the first two dataframes in the list
    merged_df = pd.merge(dfs[0], dfs[1], on=['Inning', 'Venue', 'Start_Date', 'End_Date'])

In [28]:
merged_df

,ID,Inning,Venue,Team_x,Start_Date,End_Date,Player_x,Dismissal_Type,Runs_x,Balls,...,Wickets,Maidens,Runs_y,Wides,Economy,Dot_Balls,Fours_y,Sixes_y,WD,No_Balls
0,1,1st match (N),Bengaluru,KKR,18-April-2008,18-April-2008,Sourav Ganguly c,c Kallis b Khan,10.0,12.0,...,4,0,38,0,950,13,3,3,1,0
1,1,1st match (N),Bengaluru,KKR,18-April-2008,18-April-2008,Sourav Ganguly c,c Kallis b Khan,10.0,12.0,...,4,0,38,1,950,8,3,2,0,0
2,1,1st match (N),Bengaluru,KKR,18-April-2008,18-April-2008,Sourav Ganguly c,c Kallis b Khan,10.0,12.0,...,4,0,40,1,1000,7,2,2,1,0
3,1,1st match (N),Bengaluru,KKR,18-April-2008,18-April-2008,Sourav Ganguly c,c Kallis b Khan,10.0,12.0,...,4,0,48,1,1200,9,5,3,1,0
4,1,1st match (N),Bengaluru,KKR,18-April-2008,18-April-2008,Sourav Ganguly c,c Kallis b Khan,10.0,12.0,...,3,0,26,0,866,4,0,2,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
186285,15720,Final (N),Ahmedabad,CSK,28-May-2023,29-May-2023,Ravindra Jadeja,not out,15.0,6.0,...,1,0,14,0,1400,1,1,1,1,0
186286,15720,Final (N),Ahmedabad,CSK,28-May-2023,29-May-2023,Ravindra Jadeja,not out,15.0,6.0,...,3,0,44,0,1466,2,4,3,0,0
186287,15720,Final (N),Ahmedabad,CSK,28-May-2023,29-May-2023,Ravindra Jadeja,not out,15.0,6.0,...,3,0,17,2,566,6,0,0,3,0
186288,15720,Final (N),Ahmedabad,CSK,28-May-2023,29-May-2023,Ravindra Jadeja,not out,15.0,6.0,...,2,0,30,0,1500,1,0,3,0,0
186289,15720,Final (N),Ahmedabad,CSK,28-May-2023,29-May-2023,Ravindra Jadeja,not out,15.0,6.0,...,3,0,36,3,1200,4,2,3,0,0

In [31]:
import sqlite3
import pandas as pd

# Connect to the SQLite database
conn = sqlite3.connect('./database/IPL_Prediction_Analysis.db')

# Query the Batting, Bowling, Match_Data, MVP_Data, Overs_Data, and Stats_Data tables
batting_query = '''
SELECT Innings, Venue, Start_Date, End_Date, Player_name, Dismissal_type, Runs, Balls, Minutes, Fours, Sixes, Strike_Rate
FROM Batting

'''
bowling_query = '''
SELECT Innings, Venue, Start_Date, End_Date, Bowling_Player, Overs, Maidens, Runs, Wickets, Economy_rate, Dot_ball, Fours, Sixes, Wides, No_balls
FROM Bowling

'''
match_query = '''
SELECT Innings, Venue, Start_Date, End_Date, Team1, Team2, Team1_runs, Team1_wickets, Team2_runs, Team2_wickets, Target, Team1_played_Overs, Team2_played_Overs, Team1_Max_Overs, Team2_Max_Overs, Match_Result
FROM Match_Data

'''
mvp_query = '''
SELECT Innings, Venue, Start_Date, End_Date, Player_Name, Team, Total_Impact, Runs, Balls_Faced, Impact_Runs, Batting_Impact, Wickets, Runs_Conceded, Impact_Wickets, Bowling_Impact
FROM MVP_Data

'''
overs_query = '''
SELECT Innings, Venue, Start_Date, End_Date, Team_Name, Overs, Team_Runs, Team_Wickets, Team_Total_Runs, Team_Total_Wickets
FROM Overs_Data

'''
stats_query = '''
SELECT Innings, Venue, Start_Date, End_Date, Team, Player1, Player2, Player1_Runs, Player1_Balls, Partnership_Runs, Partnership_Balls, Player2_Runs, Player2_Balls
FROM Stats_Data

'''

# Read the queries into pandas dataframes
batting_df = pd.read_sql_query(batting_query, conn)
bowling_df = pd.read_sql_query(bowling_query, conn)
match_df = pd.read_sql_query(match_query, conn)
mvp_df = pd.read_sql_query(mvp_query, conn)
overs_df = pd.read_sql_query(overs_query, conn)
stats_df = pd.read_sql_query(stats_query, conn)

# Merge the dataframes on the common columns
merged_df = pd.concat([batting_df, bowling_df, match_df, mvp_df, overs_df, stats_df], axis=1)

# Reset the index and create a new ID column
merged_df.reset_index(drop=True, inplace=True)
merged_df['Match_ID'] = merged_df.index + 1

# Save the merged data as a CSV file
merged_df.to_csv('merged_data.csv', index=False)

print(merged_df,"\n\nmerged_data.csv is created successfully")
# Close the database connection
conn.close()

Empty DataFrame
Columns: [Innings, Venue, Start_Date, End_Date, Player_name, Dismissal_type, Runs, Balls, Minutes, Fours, Sixes, Strike_Rate, Innings, Venue, Start_Date, End_Date, Bowling_Player, Overs, Maidens, Runs, Wickets, Economy_rate, Dot_ball, Fours, Sixes, Wides, No_balls, Innings, Venue, Start_Date, End_Date, Team1, Team2, Team1_runs, Team1_wickets, Team2_runs, Team2_wickets, Target, Team1_played_Overs, Team2_played_Overs, Team1_Max_Overs, Team2_Max_Overs, Match_Result, Innings, Venue, Start_Date, End_Date, Player_Name, Team, Total_Impact, Runs, Balls_Faced, Impact_Runs, Batting_Impact, Wickets, Runs_Conceded, Impact_Wickets, Bowling_Impact, Innings, Venue, Start_Date, End_Date, Team_Name, Overs, Team_Runs, Team_Wickets, Team_Total_Runs, Team_Total_Wickets, Innings, Venue, Start_Date, End_Date, Team, Player1, Player2, Player1_Runs, Player1_Balls, Partnership_Runs, Partnership_Balls, Player2_Runs, Player2_Balls, Match_ID]
Index: []

[0 rows x 82 columns]

merged_data.csv is created successfully

In [34]:
import sqlite3
import pandas as pd

# Connect to the SQLite database
conn = sqlite3.connect('./database/IPL_Prediction_Analysis.db')

# Query the Batting, Bowling, Match_Data, MVP_Data, Overs_Data, and Stats_Data tables
batting_query = '''
SELECT Innings, Venue, Start_Date, End_Date, Player_name, Dismissal_type, Runs, Balls, Minutes, Fours, Sixes, Strike_Rate
FROM Batting

'''
bowling_query = '''
SELECT Innings, Venue, Start_Date, End_Date, Bowling_Player, Overs, Maidens, Runs, Wickets, Economy_rate, Dot_ball, Fours, Sixes, Wides, No_balls
FROM Bowling

'''
match_query = '''
SELECT Innings, Venue, Start_Date, End_Date, Team1, Team2, Team1_runs, Team1_wickets, Team2_runs, Team2_wickets, Target, Team1_played_Overs, Team2_played_Overs, Team1_Max_Overs, Team2_Max_Overs, Match_Result
FROM Match_Data

'''
mvp_query = '''
SELECT Innings, Venue, Start_Date, End_Date, Player_Name, Team, Total_Impact, Runs, Balls_Faced, Impact_Runs, Batting_Impact, Wickets, Runs_Conceded, Impact_Wickets, Bowling_Impact
FROM MVP_Data

'''
overs_query = '''
SELECT Innings, Venue, Start_Date, End_Date, Team_Name, Overs, Team_Runs, Team_Wickets, Team_Total_Runs, Team_Total_Wickets
FROM Overs_Data

'''
stats_query = '''
SELECT Innings, Venue, Start_Date, End_Date, Team, Player1, Player2, Player1_Runs, Player1_Balls, Partnership_Runs, Partnership_Balls, Player2_Runs, Player2_Balls
FROM Stats_Data

'''

# Read the queries into pandas dataframes
batting_df = pd.read_sql_query(batting_query, conn)
bowling_df = pd.read_sql_query(bowling_query, conn)
match_df = pd.read_sql_query(match_query, conn)
mvp_df = pd.read_sql_query(mvp_query, conn)
overs_df = pd.read_sql_query(overs_query, conn)
stats_df = pd.read_sql_query(stats_query, conn)

In [35]:
batting_df

,Innings,Venue,Start_Date,End_Date,Player_name,Dismissal_type,Runs,Balls,Minutes,Fours,Sixes,Strike_Rate
0,1st match (N),Bengaluru,18-April-2008,18-April-2008,Sourav Ganguly c,c Kallis b Khan,10,12,,2,0,83.33
1,1st match (N),Bengaluru,18-April-2008,18-April-2008,Brendon McCullum,not out,158,73,,10,13,216.43
2,1st match (N),Bengaluru,18-April-2008,18-April-2008,Ricky Ponting,c Kumar b Kallis,20,20,,1,1,100
3,1st match (N),Bengaluru,18-April-2008,18-April-2008,David Hussey,c White b Noffke,12,12,,1,0,100
4,1st match (N),Bengaluru,18-April-2008,18-April-2008,Mohammad Hafeez,not out,5,3,,1,0,166.66
...,...,...,...,...,...,...,...,...,...,...,...,...
16747,67th Match (N),Wankhede,17-May-2024,17-May-2024,Ishan Kishan,b NaveenulHaq,14,15,50,1,0,93.33
16748,67th Match (N),Wankhede,17-May-2024,17-May-2024,Hardik Pandya c,c NaveenulHaq b Mohsin Khan,16,13,10,1,1,123.07
16749,67th Match (N),Wankhede,17-May-2024,17-May-2024,Nehal Wadhera,c Pandya b Ravi Bishnoi,1,3,3,0,0,33.33
16750,67th Match (N),Wankhede,17-May-2024,17-May-2024,Naman Dhir,not out,62,28,31,4,5,221.42
16751,67th Match (N),Wankhede,17-May-2024,17-May-2024,Romario Shepherd,not out,1,1,2,0,0,100

In [36]:
import sqlite3
import pandas as pd

# Connect to the SQLite database
conn = sqlite3.connect('./database/IPL_Prediction_Analysis.db')

# Query the Batting, Bowling, Match_Data, MVP_Data, Overs_Data, and Stats_Data tables
batting_query = '''
SELECT Innings, Venue, Start_Date, End_Date, Player_name, Dismissal_type, Runs, Balls, Minutes, Fours, Sixes, Strike_Rate
FROM Batting
'''
bowling_query = '''
SELECT Innings, Venue, Start_Date, End_Date, Bowling_Player, Overs, Maidens, Runs, Wickets, Economy_rate, Dot_ball, Fours, Sixes, Wides, No_balls
FROM Bowling
'''
match_query = '''
SELECT Innings, Venue, Start_Date, End_Date, Team1, Team2, Team1_runs, Team1_wickets, Team2_runs, Team2_wickets, Target, Team1_played_Overs, Team2_played_Overs, Team1_Max_Overs, Team2_Max_Overs, Match_Result
FROM Match_Data
'''
mvp_query = '''
SELECT Innings, Venue, Start_Date, End_Date, Player_Name, Team, Total_Impact, Runs, Balls_Faced, Impact_Runs, Batting_Impact, Wickets, Runs_Conceded, Impact_Wickets, Bowling_Impact
FROM MVP_Data
'''
overs_query = '''
SELECT Innings, Venue, Start_Date, End_Date, Team_Name, Overs, Team_Runs, Team_Wickets, Team_Total_Runs, Team_Total_Wickets
FROM Overs_Data
'''
stats_query = '''
SELECT Innings, Venue, Start_Date, End_Date, Team, Player1, Player2, Player1_Runs, Player1_Balls, Partnership_Runs, Partnership_Balls, Player2_Runs, Player2_Balls
FROM Stats_Data
'''

# Read the queries into pandas dataframes
batting_df = pd.read_sql_query(batting_query, conn)
bowling_df = pd.read_sql_query(bowling_query, conn)
match_df = pd.read_sql_query(match_query, conn)
mvp_df = pd.read_sql_query(mvp_query, conn)
overs_df = pd.read_sql_query(overs_query, conn)
stats_df = pd.read_sql_query(stats_query, conn)

# Merge the dataframes on the common columns
merged_df = batting_df.merge(bowling_df, on=['Innings', 'Venue', 'Start_Date', 'End_Date'])
merged_df = merged_df.merge(match_df, on=['Innings', 'Venue', 'Start_Date', 'End_Date'])
merged_df = merged_df.merge(mvp_df, on=['Innings', 'Venue', 'Start_Date', 'End_Date'])
merged_df = merged_df.merge(overs_df, on=['Innings', 'Venue', 'Start_Date', 'End_Date'])
merged_df = merged_df.merge(stats_df, on=['Innings', 'Venue', 'Start_Date', 'End_Date'])

# Reset the index and create a new ID column
merged_df.reset_index(drop=True, inplace=True)
merged_df['Match_ID'] = merged_df.index + 1

# Save the merged data as a CSV file
merged_df.to_csv('merged_data.csv', index=False)

print(merged_df,"\n\nmerged_data.csv is created successfully")

# Close the database connection
conn.close()

MemoryError: Unable to allocate 6.39 GiB for an array with shape (5, 171510268) and data type int64